version: "3"
services:
  db_mysql:
    image: "mariadb:10.5"
    container_name: "db_mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    ports:
      - "3306:3306"
    volumes:
      - ./data_db/database:/var/lib/mysql
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

